export type LegacyService = "user" | "events" | "admin";

export const legacyEndpoints = {
  "GetTicketsReport": "admin",
  "GetOrganizersInfoFiltered": "admin",
  "GetOrganizersEventsFiltered": "admin",
  "GetEventStatus": "events",
  "GetCancelInformation": "events",
  "CancelEvent": "events",
  "CreateEvent": "events",
  "GetTicketByOrganizer": "events",
  "CreateTickets": "user",
  "GetDashboardEvents": "events",
  "GetAdminEventByIdEvent": "events",
  "UpdateEvent": "events",
  "PublishEvent": "events",
  "GetAdminEvents": "events",
  "LogIn": "user",
  "RecoveryPassword": "user",
  "GetValidateInventoryTicket": "events",
  "UpdatePasswordRecovery": "user",
  "EditRole": "user",
  "GetRoles": "user",
  "GetRolesByAdmin": "user",
  "GetUserbyEmail": "user",
  "CreateRole": "user",
  "DeleteRole": "user",
  "GetCashierEvents": "events",
  "GetTicketByFolio": "events",
  "FullPayment": "user",
  "UpdateTicket": "events",
  "DeleteTicket": "events",
  "GetCommissionByOrganizer": "events",
  "GetEventCategory": "events",
  "GetInvoice": "user",
  "GetNeighborhoodsByZipCode": "events",
  "GetRolesByOrganizer": "user",
  "CreateOrganizerRole": "user",
  "GetAvailableRoleViews": "user",
  "DeleteOrganizerRole": "user",
  "GetOrganizerRoleDetails": "user",
  "UpdateOrganizerRole": "user",
  "CreateUser": "user",
  "DeleteUserAccount": "user",
  "GetUsers": "user",
  "UpdateUserStatus": "user",
  "ValidateCodeRecovery": "user",
  "sendRecoverPasswordEmail": "user",
  "RegenerateOrden": "user",
  "GetOrganizers": "admin",
  "GetEventsByOrganizer": "admin",
  "GetSaldoByEvent": "admin",
  "GetTransferByEvent": "admin",
  "GetTransferDetails": "admin",
  "RegisterTransferToOrganizer": "admin"
} as const;

export type LegacyEndpoint = keyof typeof legacyEndpoints;

export function getLegacyService(endpoint: LegacyEndpoint): LegacyService {
  return legacyEndpoints[endpoint];
}
